### ISSUE TITLE
First steps with Prestan

### ISSUE THREAD

**Issue by MadeinFrance** [xbenjii/Prestan#1]
I tried Prestan to list some Products that way:

```
var API_KEY         = 'secret',
    Prestan = require('prestan'),
    prestan = new Prestan('http://www.[hostname].nl/prestashop', API_KEY);

prestan.get('products', {
 schema: 'blank'
}).then(function(response) {
 console.log(response);
}).catch(function(errors) {
 console.log(errors);
});
```

But I think I got a server error, not sure but the response is not the expected one:

```
{ [Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: 4]
  cause:
   [Error: Non-whitespace before first tag.
   Line: 0
   Column: 1
   Char: 4],
  isOperational: true }
```

Any ideas for special/required settings on PrestaShop side?

**Comment by xbenjii** [comment]
How are you setting up Prestan? This error shows when Prestan can't connect via your shop URL. `http(s)://` is required at the beginning of your URL. 

I can only reproduce this with a malformed URL like

```
var prestan = new Prestan('http://http://myshop.com', 'myKey');
```

**Comment by MadeinFrance** [comment]
Thanks for the answer :)
This is how setup the library:

```
var API_KEY         = 'secret',
    Prestan              = require('prestan'),
    prestan               = new Prestan('http://www.[hostname].nl/prestashop', API_KEY);

 ...
```

**Comment by xbenjii** [comment]
I've updated the readme with debugging options.

Try doing

```
var prestan = new Prestan('http://www.[hostname].nl/prestashop', API_KEY, {debug: true});
```

**Comment by MadeinFrance** [comment]
Hey I get an error code: 401.

```
Requesting[get] http://www.mysite.nl/prestashop/api/products/?schema=blank with options {}
Error: [StatusCodeError: 401 - 401 Unauthorized]
```

The API is correct. The products XML look good:

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
 <products>
  <product id="1" xlink:href="http://mysite.nl/prestashop/api/products/1"/>
 </products>
</prestashop>
```

**Comment by xbenjii** [comment]
Sounds like the API key is wrong. What version of PrestaShop are you using?

**Comment by MadeinFrance** [comment]
Prestashop in the top left corner said version: 1.6.1.0
The API_KEY is enabled and I use a generated one?
Strange.

**Comment by xbenjii** [comment]
Does it work without requesting a schema?

**Comment by MadeinFrance** [comment]
Without requesting a schema I got the same unauthorised error.
I will try with the PSWebServiceLibrary.php and see if I have the same error response.

```
var Prestan = require('prestan'),
    prestan = new Prestan('http://www.mysite.nl/prestashop', API_KEY, {
        debug: true
    });

prestan.get('products')
.then(function(response) {
 console.log(response);
}).catch(function(errors) {
 console.log(errors);
});
```

**Comment by xbenjii** [comment]
Did you manage to replicate this issue with the PHP library?

**Comment by MadeinFrance** [comment]
No errors with php lib.
I mailed you the details.
