### ISSUE TITLE
Error Attribute without value

### ISSUE THREAD

**Issue by tundaey** [xbenjii/Prestan#10]
I followed your example exactly and i keep getting an error
[Error: "Attribute without value"
Line : 404,
Column: 45,
isOperational: true
] 

Here is my code

var Prestan = require('prestan'),
        option = {debug: true},
        prestan = new Prestan('http://xxxxxxxx.com/presta', 'xxxxxxxxxx', option);

        prestan.get('orders').then(function(response) {
            console.log("response",response);
        }).catch(function(errors) {
            console.log("errors",errors);
        });

**Comment by xbenjii** [comment]
Sounds like it's retrieving invalid XML, are you sure your path is correct?

**Comment by tundaey** [comment]
My path is http://hoverboardden.com/presta

I can view the webservice through my web browser. works fine

**Comment by tundaey** [comment]
I changed the path to http://www.hoverboardden.com/presta and it works now.

**Comment by xbenjii** [comment]
Fair enough, I don't think the request library follows redirects by default.
