### ISSUE TITLE
edit response: String could not be parsed as XML

### ISSUE THREAD

**Issue by sproit** [xbenjii/Prestan#2]
My minimal example is as follows:

``` javascript
var id = 1;
prestan.get('products', {
    id: id
}).then(function(response) {
    prestan.edit('products', {id: id}, response);
});
```

I guess the error is something that comes from the webshop itself? If you need any additional info, let me know.

A snippet from the edit request (I changed the name of the website):

Requesting[put] http://blablabla.bla/api/products/28216 with options {"form":{"putXml":"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<prestashop xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n  <product>\n    <id>28216</id>\n    <id_manufacturer xlink:href=\"https://blablabla.bla/api/manufacturers/47\">47</id_manufacturer>\n    <id_supplier>0</id_supplier>\n    <id_category_default xlink:href=\"https://blablabla.bla/api/categories/1004\">1004</id_category_default>\n    <new/>\n    <cache_default_attribute>0</cache_default_attribute>\n    <id_default_image xlink:href=\"https://blablabla.bla/api/images/products......

More error message:
Error: [StatusCodeError: 500 - <?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[127]]></code>
<message><![CDATA[XML error : String could not be parsed as XML
XML length : 9982
Original XML : putXml=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%20standalone%3D%22yes%22%3F%3E%0A%3Cprestashop%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%3E%0A%20%20%3Cproduct%3E%0A%20%20%20%20%3Cid%3E28216%3C%2Fid%3E%0A%20%20%20%20%3Cid_manufacturer%20xlink%3Ahref%3D%22......

**Comment by xbenjii** [comment]
Does indeed look like a bug. Not sure if it should be encoding it. I'll see how the PHP library does it.

**Comment by xbenjii** [comment]
Big oversight on my part for the sent parameters. Should be fixed in `1.0.13` and a1ec8119ca6471eb28306e54bcd9403eef61a8cc.

Do note that I've switched the parameters around for edit, so now it's

```
prestan.edit('products', response, {id: id});
```

**Comment by sproit** [comment]
Thanks a lot, you are great!
I had to delete some product properties before the web service would even accept an unmodified product, but that could be related to the rather old version we are running.

For reference:

``` javascript
// bullshit hack
delete response.prestashop.product.position_in_category;
delete response.prestashop.product.manufacturer_name;
delete response.prestashop.product.quantity;
```

**Comment by xbenjii** [comment]
Seems to be like that for the PHP version too, since I don't think you can edit associations from another model.
