### ISSUE TITLE
checkKeys

### ISSUE THREAD

**Issue by mccreadylemon** [xbenjii/Prestan#3]
Hello,
why are u using checkKeys? It'd like to be able to use other keys like price etc.
Check here http://doc.prestashop.com/display/PS15/Chapter+10+-+Price+management
cheers!

**Comment by xbenjii** [comment]
Oops, must've missed that one. Are there any more query parameters that are allowed to be passed or just `price`? I'd prefer to validate what gets passed rather than removing `checkKeys` all together.

**Comment by mccreadylemon** [comment]
I think just price

**Comment by mccreadylemon** [comment]
I found two more keys. <code>query</code> and <code>language</code>

**Comment by xbenjii** [comment]
I might just remove it then, knowing PrestaShop there will probably be more undocumented parameters.
