### ISSUE TITLE
delete implementation

### ISSUE THREAD

**Issue by mccreadylemon** [xbenjii/Prestan#7]
Hello,
is delete implemented?
I get 
[TypeError: Object function request(uri, options, callback) {
  if (typeof uri === 'undefined') {
    throw new Error('undefined is not a valid uri or options object.')
  }

  var params = initParams(uri, options, callback)

  if (params.method === 'HEAD' && paramsHaveRequestBody(params)) {
    throw new Error('HTTP HEAD requests MUST NOT include a request body.')
  }

  return new request.Request(params)
} has no method 'delete']

**Comment by mccreadylemon** [comment]
also here is my code

  prestan.delete('addresses', {id:3} ).then(function(response){
            console.log(response);
            }).catch(function(error) {
            console.log(error);
        });

**Comment by xbenjii** [comment]
Delete is implemented yes, can you post the full code snippet you're using?

**Comment by mccreadylemon** [comment]
is the above syntax correct?
thanks

**Comment by xbenjii** [comment]
The code looks correct, but can you post the code you're using to require and instantiate the library?

**Comment by mccreadylemon** [comment]
var config = require('./config'),
    Prestan = require('prestan'),
    options = {debug: config.production ? false : true},
    prestan = new Prestan(config.remoteUrl, config._API_KEY_ , options);

module.exports = prestan;

**Comment by mccreadylemon** [comment]
any update?

**Comment by xbenjii** [comment]
Can't reproduce it, sorry.

**Comment by liferus** [comment]
node_modules/prestan/index.js
line #177: `return this.executeRequest('delete', url).then(function (response) {`
replace: `return this.executeRequest('del', url).then(function (response) {`

**Comment by xbenjii** [comment]
@liferus That's wrong.  Closing this anyway.

**Comment by mccreadylemon** [comment]
actually that worked! thanks!
